site_name: mediatools
site_url: https://devincornell.github.io/mediatools
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
repo_url: https://github.com/devincornell/mediatools
repo_name: devincornell/mediatools